using NoSurrender.Infra.AutoGenerated;

namespace NoSurrender.Infra.Inputs
{
	public sealed class InputService
	{
		private readonly InputMaster _master;

		public InputService(InputMaster master)
		{
			_master = master;
		}
	}
}